/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as publicSignInRouteImport } from './routes/(public)/sign-in'
import { Route as publicSignUpRouteImport } from './routes/(public)/sign-up'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedHoursIndexRouteImport } from './routes/_authed/hours/index'
import { Route as AuthedHoursSettingsRouteImport } from './routes/_authed/hours/settings'
import { Route as AuthedHoursSummaryRouteImport } from './routes/_authed/hours/summary'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignInRoute = publicSignInRouteImport.update({
  id: '/(public)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignUpRoute = publicSignUpRouteImport.update({
  id: '/(public)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHoursIndexRoute = AuthedHoursIndexRouteImport.update({
  id: '/hours/',
  path: '/hours/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHoursSettingsRoute = AuthedHoursSettingsRouteImport.update({
  id: '/hours/settings',
  path: '/hours/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHoursSummaryRoute = AuthedHoursSummaryRouteImport.update({
  id: '/hours/summary',
  path: '/hours/summary',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/hours/settings': typeof AuthedHoursSettingsRoute
  '/hours/summary': typeof AuthedHoursSummaryRoute
  '/hours/': typeof AuthedHoursIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/': typeof AuthedIndexRoute
  '/hours/settings': typeof AuthedHoursSettingsRoute
  '/hours/summary': typeof AuthedHoursSummaryRoute
  '/hours': typeof AuthedHoursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/(public)/sign-in': typeof publicSignInRoute
  '/(public)/sign-up': typeof publicSignUpRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/hours/settings': typeof AuthedHoursSettingsRoute
  '/_authed/hours/summary': typeof AuthedHoursSummaryRoute
  '/_authed/hours/': typeof AuthedHoursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/hours/settings'
    | '/hours/summary'
    | '/hours/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/hours/settings'
    | '/hours/summary'
    | '/hours'
  id:
    | '__root__'
    | '/_authed'
    | '/(public)/sign-in'
    | '/(public)/sign-up'
    | '/_authed/'
    | '/_authed/hours/settings'
    | '/_authed/hours/summary'
    | '/_authed/hours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  publicSignInRoute: typeof publicSignInRoute
  publicSignUpRoute: typeof publicSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/hours/': {
      id: '/_authed/hours/'
      path: '/hours'
      fullPath: '/hours/'
      preLoaderRoute: typeof AuthedHoursIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/hours/settings': {
      id: '/_authed/hours/settings'
      path: '/hours/settings'
      fullPath: '/hours/settings'
      preLoaderRoute: typeof AuthedHoursSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/hours/summary': {
      id: '/_authed/hours/summary'
      path: '/hours/summary'
      fullPath: '/hours/summary'
      preLoaderRoute: typeof AuthedHoursSummaryRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedHoursSettingsRoute: typeof AuthedHoursSettingsRoute
  AuthedHoursSummaryRoute: typeof AuthedHoursSummaryRoute
  AuthedHoursIndexRoute: typeof AuthedHoursIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedHoursSettingsRoute: AuthedHoursSettingsRoute,
  AuthedHoursSummaryRoute: AuthedHoursSummaryRoute,
  AuthedHoursIndexRoute: AuthedHoursIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  publicSignInRoute: publicSignInRoute,
  publicSignUpRoute: publicSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
